server:
  port: 9005
spring:
  application:
    name: order-log-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev

rocketmq:
  name-server: 192.168.220.128:9876
