server:
  port: 8001

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      # 网关开启路由
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  # 配置Redis地址，用于限流
  data:
    redis:
      host: localhost
      port: 6379

# 配置日志级别，方便观察路由详情
logging:
  level:
    org.springframework.cloud.gateway: TRACE
