spring:
  profiles:
    active: dev
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        namespace: dev
        server-addr: 127.0.0.1:8848
      config:
        namespace: dev
        server-addr: 127.0.0.1:8848
        preference: remote
  config:
    import:
      nacos:shared-dev.yaml?group=dev&refreshEnabled=true
server:
  port: 9001

management:
  zipkin:
    tracing:
      endpoint: http://192.168.220.128:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 # 设置采样率为1.0，即100%追踪

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}] %-40.40logger{39} : %m%n"
