spring:
  datasource:
    url: jdbc:mysql://192.168.220.128:3306/springcloud_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        namespace: dev
        server-addr: 127.0.0.1:8848
      config:
        namespace: dev
        server-addr: 127.0.0.1:8848
        preference: remote
  config:
    import[0]:
      nacos:order-service-dev.yaml?group=dev&refreshEnabled=true
    import[1]:
      nacos:shared-dev.yaml?group=dev&refreshEnabled=true
server:
  port: 9003

management:
  endpoints:
    web:
      exposure:
        # actuator 提供的功能，暴露所有端点
        include: "*"
  zipkin:
    tracing:
      endpoint: http://192.168.220.128:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 # 采样比率100%

logging:
  pattern:
    console: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}] %-40.40logger{39} : %m%n"

rocketmq:
  name-server: 192.168.220.128:9876
  producer:
    group: order-service-producer-group


