spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 9002

management:
  zipkin:
    tracing:
      endpoint: http://192.168.220.128:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 # ??????1.0??100%??

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}] %-40.40logger{39} : %m%n"
